### ISSUE TITLE
CRITICAL BUG: mines for 20% on donate wallet....  -donate 0  does not work in version 2.7.0.2

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#542] opened 2017-11-27 03:20 UTC
-donate 0 does not work

I would consider this a critical bug for version 2.7.0.2

Miner is mining for 20% on donate wallet regardless of -donate flag

**Comment by aaronsace** [comment] 2017-11-27 09:16
It's measured in minutes. The minimum is 10 minutes (0.7%). 

Where have you got 20% from?

**Comment by alucard20724** [comment] 2017-11-27 14:17
ok... it's mining 10-12 minutes every hour

**Comment by aaronsace** [comment] 2017-11-27 14:52
Yep, not every hour in the day! Seeing as it is working as intended then I will close the issue.

**Closed by aaronsace** 2017-11-27 14:52 UTC
