### ISSUE TITLE
Vanila fail

### ISSUE THREAD

**Issue by Hardstyles** [aaronsace/MultiPoolMiner#72] opened 2017-04-04 09:24 UTC
0,00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\AMD-GenesisMining\sgminer.exe --api-listen -k vanilla -o
                                               stratum+tcp://europe.hub.miningpoolhub.com:20533 -u
                                               hardstyles.multipoolminer -p x --intensity d

[11:28:23] Started sgminer 5.5.5-gm
[11:28:23] * using Jansson 2.7
[11:28:23] Probing for an alive pool
[11:29:23] No servers were found that could be used to get work from.
[11:29:23] Please check the details from the list below of the servers you have input
[11:29:23] Most likely you have input the wrong URL, forgotten to add a port, or have not set up workers
[11:29:23] Pool: 0  URL: stratum+tcp://europe.hub.miningpoolhub.com:20533  User: hardstyles.multipoolminer  Password: x
[11:29:23] Press any key to exit, or sgminer will try again in 15s.

AMD sgminer

**Comment by aaronsace** [comment] 2017-04-04 11:44
Is this only with Vanila?

**Comment by aaronsace** [comment] 2017-04-04 11:45
Are the others fine?

**Comment by Hardstyles** [comment] 2017-04-04 14:05
only Vanilla 

Lyre2z missing Dll from first package sgminer 
mabey make a own package  
ssleay32.dll and
libeay32.dll
missing

**Comment by aaronsace** [comment] 2017-04-04 18:10
Are you sure it's not your virus checker removing files? I'll check in later but I don't think there is any files missing.

**Comment by aaronsace** [comment] 2017-04-05 11:37
MiningPoolHub home page: "Vcash forked. Closing this pool again."
Looking into the missing file issue, the files are obviously there so I'm not sure what the issue is yet.

**Comment by aaronsace** [comment] 2017-04-07 00:34
https://github.com/djm34/sgminer-msvc2015/issues/4

**Closed** 2017-05-11 09:27 UTC
