### ISSUE TITLE
Claymore benchmarks not being committed to stats.  not enough time to finish/record benchmark?

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#390] opened 2017-09-24 14:26 UTC
i have between a 50-75% failure rate of benchmarks not being recorded for claymore in the current masterbranch.     I run about 20 benchmarks from 10-200 for -dcri for each algorithm and most of them are not properly recorded and show up as 0 when recorded improperly

**Comment by alucard20724** [comment] 2017-09-24 22:40
further analysis:
multiple problems with this one.
first one, I had to remove Nicehash from my pools. I was getting massive rejects on decred from nicehash.  seems to work fine with other pools.  this probably happened with the other dual algorithms to from nicehash, but i didn't investigate further.  Removing nicehash from the pools during benchmarking solved that problem.

Second if i set the interval to 180, "-interval 180", then the benchmark appears to complete adequately. (i noticed this with some of the other algorithms also.  ewbf had the same issue, and 180 solved it.

**Comment by alucard20724** [comment] 2017-09-26 13:28
just noticed that some of the benchmarks that were properly recorded (decred and lbry) have been dropping off.   I looked into the stats and noticed that the 1,5,10,hour were zero, but the day and week still had the proper benchmark.

**Comment by fonyo** [comment] 2017-09-26 15:47
I have also noticed the same symptoms with claymore and I thought it was due to my rigs being unstable while pushing the dual-mined coins too far. I went as far as 500 dcri with smaller increments for Decred and LBRY and for both ethash and ethash2gb versions. Benchmarking took hours and more than 50% of them showed incorrect hashrate. I resolved the issue by deleting appropriate stat files for each and one by one to rebenchmark correctly. 

I also reported nicehash giving only rejects for decrednicehash as well. #380 

I believe miner configs disappearing from the list is a known issue and will be fixed in the next release. In my case, EWBF was doing this with one or two solvers randomly (decreasing hashrate recorded before disappearing). I did have issues of this kind on all my rigs with my fork of v2.6.0.2 but I only had to switch back to v2.5.2 on my 1070 rig which was just killing all the miners slowly ending up with an almost empty list after just less than a day of use. Not sure how this last report can contribute and I cannot reproduce it due to benchmarking taking too long.

**Closed** 2017-10-17 11:29 UTC
Labels: bug
