### ISSUE TITLE
SP-mod ccminer doesn't terminate

### ISSUE THREAD

**Issue by Jaerin** [aaronsace/MultiPoolMiner#171] opened 2017-06-18 03:47 UTC
Seems the spmod version of ccminer just continues to benchmark indefinitely and doesn't close the window properly.

**Comment by nemosminer** [comment] 2017-06-18 21:41
trying to add sp-mod for skein but yes it will not close atm looking into it

**Comment by Jaerin** [comment] 2017-06-18 22:48
I even tried adding the  "| stop-process –force" into the close line and it still wouldn't close it out.  I believe SP has some code in place that tries to prevent closing before a work job is complete.  May have to attempt to close it multiple times or something to force it down.

**Comment by snakethejake81** [comment] 2017-06-18 23:33
I've been using this version for months:  SP-Mod 1.5.81

I've had no issues with it closing and reopening as needed and no delays when switching algos.

**Comment by nemosminer** [comment] 2017-06-19 01:54
have you  tried it recently? i have 3 ccminers running atm Klaust , Tpruvot & sp-mod 1.5.8.1 but sp will not close for some reason i tested this a month or to ago and it was fine.. even trying to run the latest release atm hangs when it gets to sp-mod in the benchmarking.. other ccminer are closing fine..

**Comment by snakethejake81** [comment] 2017-06-19 02:54
It runs daily for skein on two different rigs.  No issues.

Sent from my iPhone

On Jun 18, 2017, at 6:54 PM, nemosminer <notifications@github.com<mailto:notifications@github.com>> wrote:


have you tried it recently? i have 3 ccminers running atm Klaust , Tpruvot & sp-mod 1.5.8.1 but sp will not close for some reason i tested this a month or to ago and it was fine.. even trying to run the latest release atm hangs when it gets to sp-mod in the benchmarking.. other ccminer are closing fine..

**Comment by Jaerin** [comment] 2017-06-19 03:07
But you still didn't answer the question.  Are you running the latest commits or your branch?  We're reporting it because it is not working on the latest commits.

**Comment by snakethejake81** [comment] 2017-06-19 06:15
Didn't know you were running latest commits (since it isn't mentioned), but no i'm running from a couple commits prior and it works without issue.

**Comment by nemosminer** [comment] 2017-06-23 04:22
any one having any luck running sp-mod yet?

**Comment by lyolyalya** [comment] 2017-06-24 04:15
what cpu do you have?and how many cards in your rig?and what kind of cards?

**Comment by Jaerin** [comment] 2017-06-24 04:30
I have 2 GPU's 1080Ti and 1080 with a i7-4970k in my main rig with this issue.

**Comment by lyolyalya** [comment] 2017-06-24 14:42
strange.i get some sort of this issue with my 4x1070 and weak cpu(athlon II x2)...after changing to fx-4300 all issues with skein are gone...as far as i know sp-mod is binding gpus to cpus(or something like that).just try to replace SP ccminer with another (tpruvot or klausT).would it be ok?

**Comment by fonyo** [comment] 2017-06-29 14:59
Can anybody else reproduce this issue?

**Comment by scaras** [comment] 2017-06-30 00:37
i have 2 pc's where ccminer tpruvot don't want to close (or opens 2 miners with different algo's) after a few hours (only use tpruvot and ccmgroestl both latest release)

**Comment by scaras** [comment] 2017-06-30 01:13
now it just happend to me the moment zpool drops away.

**Comment by Jaerin** [comment] 2017-06-30 14:34
Confirmed just tried to benchmark again and still doesn't seem to be able to close the miner.  Also I'm not sure that it is successfully reading from the API to get the hashrate since that never seems to update on the MPM screen either.

**Comment by Jaerin** [comment] 2017-06-30 15:06
Just confirmed that at least in my tests the API is not working on the SP-mod versions of ccminer at least on Windows.  Telnetting to 4068 on localhost gives a connection refused even when specifying the -b 0.0.0.0:4068 option.  Tested the same on Tpruvot and it allowed me to connect and query just fine.  perhaps an issue on the windows build of sp-mod.

**Comment by Jaerin** [comment] 2017-07-03 20:22
Just confirmed in the SP-mod post on bitcointalk that the API code has been removed.  That's likely why the latest versions aren't benchmarking correctly.

https://bitcointalk.org/index.php?topic=826901.msg19918858#msg19918858

**Comment by nemosminer** [comment] 2017-07-03 23:35
it used to work fine.. has he removed API code recently? thats a shame no other ccminer really comes close to sp-mod for skein with 6 cards...

**Comment by aaronsace** [comment] 2017-07-04 00:37
Seriously, the people that write these miners are really annoying. I'll tweak the 'wrapper.ps1' file and use that.

**Comment by Jaerin** [comment] 2017-07-04 02:52
I find that Alexis runs equal if not better than sp-mod.  That's just my experience though.  I've heard of people having problems with Alexis, but I haven't had any issues on my 6 card system.

**Comment by Jaerin** [comment] 2017-07-04 03:23
Looks like it is working for SPmod's normal ccminer, but the splbry version you'll have to modify the wrapper to match on the line like this:

```[S/A/T]: 0/50/50, diff: 3.884, 826.57MH/s yes!```

There doesn't ever seem to be a total speed or accepted  line like you are looking for now.

**Comment by nemosminer** [comment] 2017-07-04 04:29
Alexis is slightly faster but some times has a issiue of not loading up all the cards sometimes it does other times just 2-3 will go its ok for single algo as once all cards are initialized it doesn't drop them but for a algo switching miner it can be a pain

**Comment by Jaerin** [comment] 2017-07-04 04:39
Actually the wrapper doesn't seem to match the correct multiplier for the hashrate either now that I look at it.  It was showing 641GH/s for Skein when it should have been MH/s

**Comment by nemosminer** [comment] 2017-07-04 04:48
for lbry that sp-mod ccminer you are using has a 1.63% fee hardcoded.. always mines for him 1st to everytime it switches to lbry.. i find tpruvot latest version to almost match sp-modlbry and has no fee..
https://github.com/tpruvot/ccminer/releases/download/v2.0-tpruvot/ccminer-2.0-release-x64-cuda-8.0.7z

**Comment by nemosminer** [comment] 2017-07-04 05:06
i have got sp-mod working properly now for skien, x17 ,c11  skein is showing correct hashrate for me..

test rig single 1050ti:
skein ccminerklaust = 179.61 mhs
skein ccminersp-mod = 199.03 mhs

thankyou for fixing this

**Comment by Jaerin** [comment] 2017-07-04 05:16
Yeah I don't use the splbry either I just noticed that aaronsace was adding it and giving feedback on fixing it.  I hate that some of the miners have that hardcoded donation stuff built in.  If you want to offer a way to donate by all means give an option, but it shouldn't be forced.  The thing that I'm noticing is that some of the miners take a while to actually get fired up and going.  Since at least with zpool it seems like the profitability can switch pretty frequently at times, I'm wondering how much is being lost to the 30-60 seconds waiting for the new miner to get hashing.  At this point I'm probably going to bump my timeout time to 5 mins just so I make sure its not flapping so often.

**Comment by aaronsace** [comment] 2017-07-10 00:56
Mines the 2 minutes dev fee on load. Not worth it, taking Lbry out.

**Closed by aaronsace** 2017-07-10 00:56 UTC
Labels: bug, help wanted
