### ISSUE TITLE
###Request: add separate timer/interval for algos switching in MPM

### ISSUE THREAD

**Issue by lmlim** [aaronsace/MultiPoolMiner#729] opened 2017-12-18 06:30 UTC
Hi Aaronsace,

Can you add more timers/intervals counters for different kind of tasks(algos switching)? 
correct me if i am wrong, as i understand it "-interval" option applies to all kinds of tasks in your scripts.
eg: update stats, switching, benchmarking, etc... 

if i want to increase switching interval to 1 hour this would change all other timers as well right?

may be, if possible, add another timer for switching timer, but still updates stats every 60sec?

thanks

**Comment by fonyo** [comment] 2017-12-18 08:44
Setting the interval to 60 seconds does not mean it will switch every minute. MPM becomes more accurate over time as you use it.

**Comment by fonyo** [comment] 2017-12-18 08:45
*Add to FAQ, please don't close this thread*

**Comment by jayntguru** [comment] 2017-12-18 14:22
How long does it take to figure it out? If I leave the interval low it switches constantly.

   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 06 Minutes Once     Bin\Nsgminer\nsgminer.exe --api-port 14028 --api-listen --neoscrypt -o
                                               stratum+tcp://neoscrypt.mine.ahashpool.com:4233 -u
                                               1YtgTHwZgRh7rZT1fPqybkKC2ftxAaVEo -p beast.MPM,c=BTC --gpu-threads 1 --worksize 64
                                               --intensity 15 --gpu-platform 0
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\Skein-AMD\sgminer.exe --api-listen -k skeincoin -o
                                               stratum+tcp://skein.mine.ahashpool.com:4933 -u 1YtgTHwZgRh7rZT1fPqybkKC2ftxAaVEo
                                               -p beast.MPM,c=BTC --gpu-threads 2 --worksize 256 --intensity d --gpu-platform 0

**Comment by fonyo** [comment] 2017-12-18 14:43
It should not, can you post your log file? What are your rig's specs?

**Comment by lmlim** [comment] 2017-12-18 15:23
@fonyo I have seen cases MPM switched algos after running a few minutes, even after i have reduced to only 4 algos. 
in my algos option list, i only have 4: cryptonight, ethhash, ethash2gb, equihash.
poolnames are only miningpoolhub and miningpoolhubcoins
yet I want to further minimize jumping by set it 1hour interval and also minimize first 15min devfee.

since MPH uses PPLNS, this is the way to do mining optimally?
do you think 1 hour interval wont help at all?

**Comment by jayntguru** [comment] 2017-12-18 17:13
@fonyo I will post a log shortly.

-JS

**Comment by jayntguru** [comment] 2017-12-18 18:53
[2017-12-18_08-56-10.txt](https://github.com/aaronsace/MultiPoolMiner/files/1569115/2017-12-18_08-56-10.txt)
[2017-12-18_09-02-07.txt](https://github.com/aaronsace/MultiPoolMiner/files/1569117/2017-12-18_09-02-07.txt)

Here's two logs from two machines.

I pretty much don't want it to mine anything less than an hour.

-JS

**Comment by aaronsace** [comment] 2017-12-18 18:56
@jayntguru

The problem is not MiningPoolHub but the other pools. It's quite safe to switch on pools that run prop. 

This should resolve your issue: 
https://github.com/aaronsace/MultiPoolMiner/commit/82770d2d1c0a9f8285905e2ece0600d1bd219906

**Comment by jayntguru** [comment] 2017-12-18 20:51
@aaronsace 

You mean MPH is the one you want to stay on and the others can switch? Or vice versa?

**Closed** 2017-12-19 20:04 UTC
Labels: question
