### ISSUE TITLE
Decimal error  in log file attached

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#124] opened 2017-05-28 07:02 UTC
[2017-05-28_09-00-06.txt](https://github.com/aaronsace/MultiPoolMiner/files/1034001/2017-05-28_09-00-06.txt)

**Comment by imrecsoka** [comment] 2017-05-28 07:15
I have attached the log file in plain text 
It started happening all of as sudden.
I was having clean runs though.

**Comment by aaronsace** [comment] 2017-05-28 09:14
Is this the same include file that you are using?
https://github.com/aaronsace/MultiPoolMiner/blob/master/Include.ps1

**Comment by aaronsace** [comment] 2017-05-28 09:17
I'm using 'double' now instead of 'decimal' so I'm a bit confused.

**Comment by imrecsoka** [comment] 2017-05-28 19:56
If i download your lastest ZIP file, extract and run then it works perfectly. 
Hours later something went wrong and my pc rebooted know idea why.
I then just restarted the start.bat and i get this weird decimal error... not sure why.
I have re-downloaded your new version and i am running the benchmarks now , again.

**Comment by imrecsoka** [comment] 2017-05-29 10:56
Hi, this is crazy man, that decimal error came back.
I then decided to download your include.ps1 in your link above.
Now i get this horrible bunch or errors:
![image](https://cloud.githubusercontent.com/assets/25494601/26547228/39e63dac-446e-11e7-9c4a-52467c440390.png)

**Comment by imrecsoka** [comment] 2017-05-29 10:59
I deleted that include.ps1 and i put back my old include file.
This is what the originalinclude.ps1 file looks like (attached as .txt)
[Include.txt](https://github.com/aaronsace/MultiPoolMiner/files/1035626/Include.txt)
I extracted this as is from your latest multi miner, i dont understand what this decimal error is.

**Comment by fonyo** [comment] 2017-05-30 04:24
I get a lot of these as well lately. The cause is most likely the lack of response from the web (which may or may not be due to dropped packages/connectivity). And then it just can't reset itself properly. Reloading MPM does seem to fix it but then there are lots of messages with decimal too large or too small.

**Comment by fonyo** [comment] 2017-05-30 04:27
Reading web response bar is stuck on the top. MPM doesn't seem to refresh at all.
Include.ps1:112 char 42 argument exception 
Invalid JSON primitive

**Comment by aaronsace** [comment] 2017-05-30 11:19
Fixed in upcoming release.

**Closed by aaronsace** 2017-05-30 11:19 UTC
