### ISSUE TITLE
Issue with Miner adding NVIDIA when specified otherwise

### ISSUE THREAD

**Issue by HotRod11686** [aaronsace/MultiPoolMiner#537] opened 2017-11-26 18:50 UTC
Hello,

For whatever reason whenever I start up the multipoolminer with the batch file specified that i want AMD only it always loads up adding NVIDIA. I am using version 2.7.0.2

Below is my start.bat file 

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username HotRod -workername 290 -region usa -type AMD,CPU -poolname miningpoolhub -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib -watchdog"

**Comment by aaronsace** [comment] 2017-11-29 19:11
Please attach the log.

**Comment by HotRod11686** [comment] 2017-11-30 01:54
[2017-11-29_03-55-16.txt](https://github.com/aaronsace/MultiPoolMiner/files/1516273/2017-11-29_03-55-16.txt)

**Comment by UselessGuru** [comment] 2017-11-30 07:22
@HotRod11686 

You have two miners that support AMD as well as NVIDIA:

>    Type: {AMD, NVIDIA}
Miner      Algorithm      Speed BTC/Day BTC/GH/Day Pool
\-\-\-\-\-       \-\-\-\-\-\-\-\-\-      \-\-\-\-\- \-\-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\- \-\-\-\-
Eminer     Ethash2gb 20.13 MH/s 0.00015    0.00741 MiningPoolHubCoins-Musicoin
Prospector Ethash    14.93 MH/s 0.00011    0.00757 MiningPoolHub-Ethereum

This is nothing you should worry about and is purely cosmetic.

**Comment by lee-aaron** [comment] 2017-12-02 06:57
Closing as this is not a bug and seems to be resolved.

**Closed by lee-aaron** 2017-12-02 06:57 UTC
