### ISSUE TITLE
All algo error

### ISSUE THREAD

**Issue by rhadamants** [aaronsace/MultiPoolMiner#126] opened 2017-06-01 02:28 UTC
All algo give me 0 hashrate. Using gtx 1080 and 1070 e only cpu miner works using this multipoolminer.

**Comment by aaronsace** [comment] 2017-06-01 07:52
There is a lot of miners; if not a single one is working then there must be something up with your system. 
Maybe check your drivers?

**Comment by aaronsace** [comment] 2017-06-01 14:58
Also, make sure they are not being blocked by firewall or virus checker.

**Comment by rhadamants** [comment] 2017-06-01 16:00
Using only win10. Using this miners with bat works fine but not work using this your json files.

**Comment by rhadamants** [comment] 2017-06-01 16:24
Bat with normal commands works. Bat with yours comands and yours json files not work.

**Comment by aaronsace** [comment] 2017-06-01 17:40
Please can you clarify, when it benchmarks for the first time, can you see the miners appear?

**Comment by aaronsace** [comment] 2017-06-01 17:44
If you see the miners appear, are they working?

**Comment by aaronsace** [comment] 2017-06-01 17:47
If the answer to the above questions is yes, then it's you firewall.

**Comment by rhadamants** [comment] 2017-06-01 18:09
Miners appear but give 0 hashrate. Only cpu miners give hashrate numbers. This open 5 miners one for json0 - json5 files. but no hashrate. Firewall windows 10 only.

**Comment by aaronsace** [comment] 2017-06-01 18:21
Please can you screenshot? I'm getting lost with this.

**Comment by aaronsace** [comment] 2017-06-01 18:23
Can you upload the log as well.

**Comment by rhadamants** [comment] 2017-06-01 19:07
[Logs.zip](https://github.com/aaronsace/MultiPoolMiner/files/1045773/Logs.zip)

**Comment by aaronsace** [comment] 2017-06-01 20:31
There is commas (,) in your numbers. It should be decimal points (.). 

I'll have to look into what's causing that. What language is your operating system set to?

**Comment by aaronsace** [comment] 2017-06-01 21:40
Ok, worked out that it's Spanish. I can reproduce that error if I read a file in with a comma but I haven't yet figured out yet how the comma is appearing in the stat files. When it writes the file it shouldn't be Spanish.

**Comment by aaronsace** [comment] 2017-06-02 08:06
In the 'MultiPoolMiner.ps1' please can you try inserting this line and let me know if it works: 

```
)

Set-Location (Split-Path $script:MyInvocation.MyCommand.Path)

Get-ChildItem . -Recurse | Unblock-File
```

**Comment by rhadamants** [comment] 2017-06-02 12:33
MultiPoolMiner.ps1 is fine now but using bat give 0.00hashrate.

**Comment by aaronsace** [comment] 2017-06-02 13:39
So was the issue isolated to the 'start.bat' file? 
Was there never a issue to begin with when using MultiPoolMiner.ps1 directly?

**Comment by Ondalf** [comment] 2017-06-02 13:52
There is nothing wrong with this thing. Its doing benchmark and the miner stats at down will be set at 0 after 2 cycles. Commas and dots work. Powershell knows, what to use. fi_FI Win10 here, and been using this script for a while. Simply put, let it run benchmark. It seems to register values anyhow.

**Comment by rhadamants** [comment] 2017-06-02 14:01
Before using his modification happened in both. Now it only happens using the bat.
How do I just use benchmark only? Here only be mining equihash even Lbry being worth more.

**Comment by Ondalf** [comment] 2017-06-02 14:22
Hmm, after doing changes, since it complains the files inside Stats folder, can you empty it? Which day you downloaded the script from here? Tried updating to current and destroying Stats folder, after copying over?

**Comment by rhadamants** [comment] 2017-06-02 14:36
Excavator sia and equihash give 0 hashrate. Use the last commit

**Comment by Ondalf** [comment] 2017-06-02 14:41
Excavator Sia should give 0, since its equihash-only and nheqminer is wonky, and seemed to work with 1080 only (in my computer). Excavator is way faster for equihash, so don't worry about it.

**Comment by aaronsace** [comment] 2017-06-02 18:55
https://github.com/nicehash/excavator/releases

**Comment by fonyo** [comment] 2017-06-29 14:45
There hasn't been an update for almost a month. I am closing the thread. If the issue persists, please create a NEW one.

**Closed by fonyo** 2017-06-29 14:45 UTC
