### ISSUE TITLE
driver crash on closing ccminer

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#4] opened 2016-12-15 05:18 UTC
what is a bad luck and how to fight it...according to your scrypt need to close ccminer even when i switch from neoscrypt to skein or groest.in this case i have driver crash on closing ccminer and my gpu0 is gone until system restart.no overclock.this is ccminer bug i guess, but default multipoolhubs multialgo swithing with a single doswindow works fine.is it possibe to run all miners in a single doswindow somehow?

**Comment by aaronsace** [comment] 2016-12-15 08:30
Yes but it is more complex and would be miner specific; it's a possibility at some point but not right now. There must something either wrong with your gpu or ccminer. All it's doing is opening and closing different miners. If you have to reboot your system to fix it then I would say the problem is with your gpu.

**Comment by lyolyalya** [comment] 2016-12-15 08:39
but skein or neoscrypt on zpool with algo switching with overclock works fine for few days without any trouble...

**Comment by aaronsace** [comment] 2016-12-15 09:11
Try a different driver version and maybe try posting a log file on a ccminer forum. I will try and look into a solution but I have no NVidia card and no knowledge of ccminer.

**Comment by lyolyalya** [comment] 2016-12-15 09:17
ccminer does not write logs by default=( maybe -S will work.i'll try.
i already tried tdrdelay, and some videofile in background...latest drivers, win 8.1 x64...maybe win10 will help...

**Comment by lyolyalya** [comment] 2016-12-16 10:12
yep...i install win 10 and crashes are gone.some problems with miner instead but there is small things...strange...

**Closed** 2016-12-16 10:13 UTC
