### ISSUE TITLE
stats doesn't always show.

### ISSUE THREAD

**Issue by r1rider01** [aaronsace/MultiPoolMiner#736] opened 2017-12-18 18:34 UTC
Having a slight issue,   the main .bat file will go blank....and when i hit enter I get the full stats page.

other times it will display some of the info, but doesn't show this part
"
Miner       Pool          Algorithm Watchdog Timer
-----       ----          --------- --------------
NsgminerAmd MiningPoolHub NeoScrypt      0 Seconds

MultiPoolMiner is between 36% and 55% more profitable than the fastest miner:

Miner              BTC                             USD
-----              ---                             ---
MultiPoolMiner     0.00132 ±17 % (0.00113-0.00155) 24.56553 ±17 % (20.99982-28.73669)
ClaymoreAmd-Ethash 0.00091 ±2 % (0.00089-0.00092)  16.87871 ±2 % (16.61983-17.14162)
"

which is really the information i want to see

ideas?

**Comment by aaronsace** [comment] 2017-12-18 18:38
It's because you clicked on the window.

**Comment by r1rider01** [comment] 2017-12-18 18:46
which window?

**Comment by r1rider01** [comment] 2017-12-18 18:50
I have shut everything down.....ran the bat file and haven't touched anything since.      still doesn't display the detailed stats about BTC/USD and multipoolminer is % more profitable

**Comment by jayntguru** [comment] 2017-12-18 18:51
This is a duplicate of this one.

https://github.com/aaronsace/MultiPoolMiner/issues/711

**Comment by aaronsace** [comment] 2017-12-18 18:51
That's not the issue you described above. 
https://github.com/aaronsace/MultiPoolMiner/issues/711

**Closed by aaronsace** 2017-12-18 18:51 UTC

**Comment by r1rider01** [comment] 2017-12-18 18:59
i had 2 issues.... one was the screen would just be blank....the other is it doesn't display the details as stated in #711
